
# This is a basic workflow to help you get started with Actions

name: Publish

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-terraform:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: pack .\terraform\terraform.nuspec

      - name: Choco install
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install -source . -force terraform

      - name: Terraform Version
        run: terraform -version
      
      - name: Save Choco package
        uses: actions/upload-artifact@v2
        with:
          name: terraform
          path: "${{ github.workspace }}/*.nupkg"
          
  publish-terraform:
    runs-on: windows-latest
    
    needs: build-terraform
      
    steps:
      - uses: actions/checkout@v2

      - name: Restore Choco package
        uses: actions/download-artifact@v2
        with:
          name: terraform
          path: ${{ github.workspace }}
       
      - name: Terraform Version
        run: terraform -version
        
      - name: Add Choco API Key
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: apikey --key ${{secrets.choco_api_key}} --source https://push.chocolatey.org/
        
      - name: Publish (noop)
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: push --noop
      
