name: Publish

on:
  push:
    branches:
      - develop
    paths-ignore:
      - .github/**

jobs:
  build-terraform:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v2.1.0
        with:
          args: pack .\terraform\terraform.nuspec

      - name: Choco install
        uses: crazy-max/ghaction-chocolatey@v2.1.0
        with:
          args: install -source . -force terraform

      - name: Terraform Version
        run: terraform -version

      - name: Save Choco package
        uses: actions/upload-artifact@v3
        with:
          name: terraform
          path: "${{ github.workspace }}/*.nupkg"

  publish-terraform:
    runs-on: windows-latest

    needs: build-terraform

    steps:
      - uses: actions/checkout@v3

      - name: Restore Choco package
        uses: actions/download-artifact@v3
        with:
          name: terraform
          path: ${{ github.workspace }}

      - name: Choco install
        uses: crazy-max/ghaction-chocolatey@v2.1.0
        with:
          args: install -source . -force terraform

      - name: Terraform Version
        run: terraform -version

      - name: Add Choco API Key
        uses: crazy-max/ghaction-chocolatey@v2.1.0
        with:
          args: apikey --key ${{secrets.CHOCO_API_KEY}} --source https://push.chocolatey.org/

      - name: Publish (noop)
        uses: crazy-max/ghaction-chocolatey@v2.1.0
        with:
          args: push
