name: Test

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.UPDATING_GITHUB_TOKEN }}

      - name: Install AU dependencies
        run: choco install Chocolatey-AU -y

      - name: Update Terraform
        working-directory: ${{ github.workspace }}/terraform
        run: .\update.ps1

      - name: Save Chocolatey packages
        uses: actions/upload-artifact@v7
        with:
          name: terraform
          path: "${{ github.workspace }}\\terraform\\*.nupkg"
