name: Update Terraform

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
    paths-ignore:
      - .github/**

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install AU dependencies
        uses: crazy-max/ghaction-chocolatey@v3.0.0
        with:
          args: install Chocolatey-AU wormies-au-helpers

      - name: Update Terraform
        shell: pwsh
        working-directory: ${{ github.workspace }}/terraform
        run: .\update.ps1

      - name: Save Chocolatey packages
        uses: actions/upload-artifact@v4
        with:
          name: terraform
          path: "${{ github.workspace }}\\terraform\\*.nupkg"

      - name: Commit and push changes
        env:
          COMMIT_MESSAGE: "Update Terraform Chocolatey packages"
          COMMIT_AUTHOR: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          COMMIT_USER_NAME: "github-actions[bot]"
          COMMIT_USER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
        run: |
          git add .
          git -c user.name="$INPUT_COMMIT_USER_NAME" -c user.email="$INPUT_COMMIT_USER_EMAIL" \
            commit -m "$INPUT_COMMIT_MESSAGE" \
            --author="$INPUT_COMMIT_AUTHOR"
          # git push -u origin ${{ github.ref_name }}
          git push -u origin feature/auto-updating
